name: zestimater
description: A library for scraping Zillow Zestimates for a given address.
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  html: ^0.15.6
  http: ^1.5.0
  intl: ^0.20.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
